version: '2'
services:
    gtbee-app:
        image: gtbee
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://gtbee-postgresql:5432/GTBee
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8081:8081
    gtbee-postgresql:
        extends:
            file: postgresql.yml
            service: gtbee-postgresql
